const ageSpecialties = {
  "ageSpecialty/toddlers": "Toddlers / Preschoolers (0 to 6)",
  "ageSpecialty/children": "Children (6 to 10)",
  "ageSpecialty/preteens": "Preteens / Tweens (11 to 13)",
  "ageSpecialty/adolescents": "Adolescents / Teenagers (14 to 19)",
  "ageSpecialty/adults": "Adults",
  "ageSpecialty/elders": "Elders (65+)"
};

const conditions = {
  "condition/academicUnderachievement": "Academic Underachievement",
  "condition/addiction": "Addiction",
  "condition/ADHD": "ADHD",
  "condition/ADHDADD": "ADHD/ADD",
  "condition/adjustment": "Adjustment",
  "condition/adoption": "Adoption",
  "condition/alcoholAbuse": "Alcohol Abuse",
  "condition/alzheimers": "Alzheimer's",
  "condition/angerManagement": "Anger Management",
  "condition/antisocialPersonality": "Antisocial Personality",
  "condition/anxiety": "Anxiety",
  "condition/aspergersSyndrome": "Asperger's Syndrome",
  "condition/autism": "Autism",
  "condition/behavioralIssues": "Behavioral Issues",
  "condition/bereavementGrief": "Bereavement/Grief",
  "condition/bipolarDisorder": "Bipolar Disorder",
  "condition/bisexualIssues": "Bisexual Issues",
  "condition/bodyImage": "Body Image",
  "condition/borderlinePersonality": "Borderline Personality",
  "condition/careerCounseling": "Career Counseling",
  "condition/childOrAdolescent": "Child Adolescent",
  "condition/chronicImpulsivity": "Chronic Impulsivity",
  "condition/chronicPain": "Chronic Pain",
  "condition/chronicRelapse": "Chronic Relapse",
  "condition/codependency": "Codependency",
  "condition/controlIssues": "Control Issues",
  "condition/copingSkills": "Coping Skills",
  "condition/depression": "Depression",
  "condition/developmentalDisorders": "Developmental Disorders",
  "condition/dissociativeDisorders": "Dissociative Disorders",
  "condition/divorce": "Divorce",
  "condition/domesticAbuse": "Domestic Abuse",
  "condition/domesticViolence": "Domestic Violence",
  "condition/drugAbuse": "Drug Abuse",
  "condition/dualDiagnosis": "Dual Diagnosis",
  "condition/eatingDisorders": "Eating Disorders",
  "condition/elderlyPersonsDisorders": "Elderly Persons Disorders",
  "condition/emotionalDisturbance": "Emotional Disturbance",
  "condition/entitlement": "Entitlement",
  "condition/familyConflict": "Family Conflict",
  "condition/gambling": "Gambling",
  "condition/gayIssues": "Gay Issues",
  "condition/grief": "Grief",
  "condition/impulseControlDisorders": "Impulse Control Disorders",
  "condition/infertility": "Infertility",
  "condition/infidelity": "Infidelity",
  "condition/intellectualDisability": "Intellectual Disability",
  "condition/internetAddiction": "Internet Addiction",
  "condition/isolation": "Isolation",
  "condition/learningDisabilities": "Learning Disabilities",
  "condition/lesbianIssues": "Lesbian Issues",
  "condition/lifeCoaching": "Life Coaching",
  "condition/manipulation": "Manipulation",
  "condition/maritalAndPremarital": "Marital Premarital",
  "condition/medicalDetox": "Medical Detox",
  "condition/medicalIssues": "Medical Issues",
  "condition/medicationManagement": "Medication Management",
  "condition/mensIssues": "Mens Issues",
  "condition/moodDisorders": "Mood Disorders",
  "condition/narcissisticPersonality": "Narcissistic Personality",
  "condition/obesity": "Obesity",
  "condition/OCD": "OCD",
  "condition/oppositionalDefiance": "Oppositional Defiance",
  "condition/other": "Other",
  "condition/otherIssues": "Other Issues",
  "condition/paranoia": "Paranoia",
  "condition/parenting": "Parenting",
  "condition/peerRelationships": "Peer Relationships",
  "condition/personalityDisorders": "Personality Disorders",
  "condition/phobia": "Phobia",
  "condition/postpartumDepression": "Postpartum Depression",
  "condition/pregnancy": "Pregnancy",
  "condition/pregnancyPrenatalPostpartum": "Pregnancy Prenatal Postpartum",
  "condition/psychosis": "Psychosis",
  "condition/PTSD": "PTSD",
  "condition/relationshipIssues": "Relationship Issues",
  "condition/SAD": "SAD",
  "condition/schizophrenia": "Schizophrenia",
  "condition/selfEsteem": "Self Esteem",
  "condition/selfHarming": "Self Harming",
  "condition/sexTherapy": "Sex Therapy",
  "condition/sexualAbuse": "Sexual Abuse",
  "condition/sexualAddiction": "Sexual Addiction",
  "condition/sleepOrInsomnia": "Sleep or Insomnia",
  "condition/smokingCessation": "Smoking Cessation",
  "condition/somatization": "Somatization",
  "condition/spirituality": "Spirituality",
  "condition/stress": "Stress",
  "condition/substanceAbuse": "Substance Abuse",
  "condition/suicidalIdeation": "Suicidal Ideation",
  "condition/teenViolence": "Teen Violence",
  "condition/testingAndEvaluation": "Testing and Evaluation",
  "condition/thinkingDisorders": "Thinking Disorders",
  "condition/transgenderIdentity": "Transgender Identity",
  "condition/trauma": "Trauma",
  "condition/traumaticBrainInjury": "Traumatic Brain Injury",
  "condition/videoGameAddiction": "Video Game Addiction",
  "condition/weightLoss": "Weight Loss",
  "condition/womensIssues": "Womens Issues"
}

const insurances = {
  "insurance/AARP": "AARP",
  "insurance/ACISpecialtyBenefits": "ACI Specialty Benefits",
  "insurance/aetna": "Aetna",
  "insurance/affinityHealthPlan": "Affinity Health Plan",
  "insurance/alliance": "Alliance",
  "insurance/americanBehavioral": "American Behavioral",
  "insurance/AMERIGROUP": "AMERIGROUP",
  "insurance/ameriHealth": "Ameri Health",
  "insurance/anthem": "Anthem",
  "insurance/APSHealthcare": "APS Healthcare",
  "insurance/beacon": "Beacon",
  "insurance/beechStreet": "Beech Street",
  "insurance/behavioralHealthSystems": "Behavioral Health Systems",
  "insurance/blueCareNetwork": "Blue Care Network of Michigan",
  "insurance/blueCrossAndBlueShield": "Blue Cross And Blue Shield",
  "insurance/blueCrossAndBlueShieldMA": "Blue Cross And Blue Shield MA",
  "insurance/blueShieldOfNortheasternNewYork": "BlueShield of Northeastern New York",
  "insurance/BMCHealthNet": "BMC HealthNet",
  "insurance/careSource": "CareSource",
  "insurance/cascadeHealth": "Cascade Health",
  "insurance/CCN": "CCN",
  "insurance/CDPHP": "CDPHP",
  "insurance/celticare": "CeltiCare Health",
  "insurance/cenpatico": "Cenpatico",
  "insurance/ceridian": "Ceridian",
  "insurance/CHAMPVA": "CHAMPVA",
  "insurance/chickering": "The Chickering Group",
  "insurance/CHIPA": "CHIPA",
  "insurance/choiceCare": "Choice Care",
  "insurance/cigna": "Cigna",
  "insurance/communityCareBehavioralHealth": "Community Care Behavioral Health",
  "insurance/comPsych": "ComPsych",
  "insurance/comPsychEAP": "ComPsych EAP",
  "insurance/connectiCare": "ConnectiCare",
  "insurance/corphealth": "Corp health",
  "insurance/coventry": "Coventry",
  "insurance/deerOaks": "Deer Oaks",
  "insurance/devon": "Devon Health Services",
  "insurance/E4HealthEAP": "E4 Health EAP",
  "insurance/emblemHealth": "Emblem Health",
  "insurance/empireBlueCross": "Empire Blue Cross",
  "insurance/empirePlan": "The Empire Plan",
  "insurance/fallonHealth": "Fallon Health",
  "insurance/fidelis": "Fidelis",
  "insurance/firstChoiceHealth": "First Choice Health",
  "insurance/firstHealth": "First Health",
  "insurance/gateway": "Gateway",
  "insurance/GEHA": "GEHA",
  "insurance/GHI": "GHI",
  "insurance/greatWest": "Great West",
  "insurance/greenShieldCanada": "Green Shield Canada",
  "insurance/groupHealth": "Group Health",
  "insurance/groupInsuranceCommissionGIC": "Group Insurance Commission (GIC) ",
  "insurance/guardian": "Guardian",
  "insurance/HAPHealthAlliancePlan": "HAP Health Alliance Plan",
  "insurance/harvardPilgrim": "Harvard Pilgrim",
  "insurance/HCVM": "HCVM",
  "insurance/healthAdvocateEAP": "Health Advocate EAP",
  "insurance/healthAmericaHealthAssurance": "HealthAmerica/HealthAssurance",
  "insurance/healthChoice": "Health Choice",
  "insurance/healthFirst": "HealthFirst",
  "insurance/healthLink": "Health Link",
  "insurance/healthNet": "Health Net",
  "insurance/healthNewEngland": "Health New England",
  "insurance/healthPartners": "HealthPartners",
  "insurance/healthRepublicOfNewYork": "Health Republic Insurance of New York",
  "insurance/HFN": "HFN",
  "insurance/highmark": "Highmark",
  "insurance/highmarkMedicareAdvantage": "Highmark Medicare Advantage",
  "insurance/HIPHealthPlanOfNewYork": "HIP Health Plan Of New York",
  "insurance/HMAA": "HMAA",
  "insurance/HMSA": "HMSA",
  "insurance/HNE": "HNE",
  "insurance/holmanGroup": "HolmanGroup",
  "insurance/horizon": "Horizon",
  "insurance/HSBC": "HSBC",
  "insurance/hudsonHealthPlan": "Hudson Health Plan",
  "insurance/humana": "Humana",
  "insurance/husky": "Husky",
  "insurance/indemnity": "Indemnity",
  "insurance/integratedHealthPlan": "IntegratedHealth Plan",
  "insurance/intergroup": "InterGroup Services",
  "insurance/interplan": "Interplan",
  "insurance/kaiser": "Kaiser",
  "insurance/lifeSolutionEAP": "Life's Solutions EAP",
  "insurance/lifeSynch": "LifeSynch",
  "insurance/lifeWise": "LifeWise",
  "insurance/magellanBehavioralHealth": "Magellan Behavioral Health",
  "insurance/magellanEAP": "Magellan EAP",
  "insurance/magnaCare": "Magna Care",
  "insurance/massachusettsBehavioralHealthPartnershipMBHP": "Massachusetts Behavioral Health Partnership",
  "insurance/massHealth": "Mass Health",
  "insurance/medicaid": "Medicaid",
  "insurance/medicaidMA": "Medicaid MA",
  "insurance/medicaidPA": "Medicaid PA",
  "insurance/medicalMutual": "Medical Mutual",
  "insurance/medicare": "Medicare",
  "insurance/medicarePA": "Medicare PA",
  "insurance/meridian": "Meridian",
  "insurance/metroPlus": "MetroPlus Health Plan",
  "insurance/MHN": "MHN",
  "insurance/MHNetBehavioralHealth": "MHNet Behavioral Health",
  "insurance/militaryOneSource": "Military OneSource",
  "insurance/MINES": "MINES",
  "insurance/minutemenHealth": "Minuteman Health",
  "insurance/modaHealth": "Moda Health",
  "insurance/multiplan": "MultiPlan",
  "insurance/MVP": "MVP",
  "insurance/NCPPO": "NCPPO",
  "insurance/neighborhoodHealth": "Neighborhood Health",
  "insurance/neighborhoodHealthPlan": "Neighborhood Health Plan",
  "insurance/networkHealth": "Network Health",
  "insurance/novitasMedicare": "Novitas Solutions, Inc.",
  "insurance/optima": "Optima",
  "insurance/optum": "Optum",
  "insurance/oscarHealthInsuranceCo": "Oscar",
  "insurance/other": "Other",
  "insurance/outOfNetwork": "Out of network",
  "insurance/oxford": "Oxford",
  "insurance/pacifiCare": "PacifiCare",
  "insurance/pacificSource": "Pacific Source",
  "insurance/pennsylvaniaDepartmentOfPublicWelfare": "Pennsylvania Department of Public Welfare",
  "insurance/performCare": "PerformCare",
  "insurance/PHCS": "PHCS",
  "insurance/pioneer": "Pioneer",
  "insurance/POMCO": "POMCO",
  "insurance/preferredOne": "PreferredOne",
  "insurance/premera": "Premera",
  "insurance/premeraMedicareAdvantage": "Premera Medicare Advantage",
  "insurance/providence": "Providence",
  "insurance/psychCare": "PsychCare",
  "insurance/regence": "Regence",
  "insurance/reliant": "Reliant",
  "insurance/seniorWholeHealthOfMASWHMA": "Senior Whole Health of MASW HMA",
  "insurance/soundPath": "Soundpath Health",
  "insurance/theWellnessCorporation": "The Wellness Corporation",
  "insurance/threeRiversProvidersNetworkTRPN": "Three Rivers Provider Network: TRPN",
  "insurance/TRICARE": "TRICARE",
  "insurance/triWest": "TriWest Healthcare Alliance",
  "insurance/tufts": "Tufts",
  "insurance/tuftsHealthDirect": "Tufts Health Direct",
  "insurance/uCare": "uCare",
  "insurance/UMR": "UMR",
  "insurance/uniCare": "Unicare",
  "insurance/unitedBehavioralHealth": "United BehavioralHealth",
  "insurance/unitedHealthCare": "UnitedHealthcare",
  "insurance/unitedHealthcareWorkersEast1199SEIU": "1199SEIU Healthcare Workers East",
  "insurance/UPMC": "UPMC",
  "insurance/UPMCHealthPlanMedicareAdvantage": "UPMC Health Plan Medicare Advantage",
  "insurance/valueBehavioralHealth": "Value Behavioral Health of Pennsylvania",
  "insurance/valueOptions": "ValueOptions",
  "insurance/vytra": "Vytra",
  "insurance/wellCare": "WellCare",
  "insurance/wellpoint": "WellPoint"
};

const languages = {
  "language/arabic": "Arabic",
  "language/cantonese": "Cantonese",
  "language/english": "English",
  "language/french": "French",
  "language/german": "German",
  "language/hindi": "Hindi",
  "language/italian": "Italian",
  "language/japanese": "Japanese",
  "language/korean": "Korean",
  "language/mandarin": "Mandarin",
  "language/polish": "Polish",
  "language/portuguese": "Portuguese",
  "language/russian": "Russian",
  "language/serbian": "Serbian",
  "language/spanish": "Spanish",
  "language/tagalog": "Tagalog",
  "language/vietnamese": "Vietnamese"
};

const providerTypes = {
  "providerType/artTherapist": "Art Therapist",
  "providerType/centralIntake": "Central Intake",
  "providerType/clinicalSocialWorkTherapist": "Clinical Social Work Therapist",
  "providerType/counselor": "Counselor",
  "providerType/curbside": "Curbside",
  "providerType/drugAlcoholCounselor": "Drug Alcohol Counselor",
  "providerType/LCSW": "LCSW",
  "providerType/licensedPsychoanalyst": "Licensed Psychoanalyst",
  "providerType/LICSW": "LICSW",
  "providerType/limitedLicensedPsychologist": "Limited Licensed Psychologist",
  "providerType/LMHC": "LMHC",
  "providerType/LPC": "LPC",
  "providerType/LPCIntern": "LPC Intern",
  "providerType/marriageFamilyTherapist": "Marriage Family Therapist",
  "providerType/marriageFamilyTherapistIntern": "Marriage Family Therapist Intern",
  "providerType/naturopathicPhysician": "Naturopathic Physician",
  "providerType/occupationalTherapist": "Occupational Therapist",
  "providerType/other": "Other",
  "providerType/pastoralCounselor": "Pastoral Counselor",
  "providerType/preLicensedProfessional": "Pre Licensed Professional",
  "providerType/psychiatricNurse": "Psychiatric Nurse",
  "providerType/psychiatrist": "Psychiatrist",
  "providerType/psychologicalAssociate": "Psychological Associate",
  "providerType/psychologist": "Psychologist",
  "providerType/treatmentFacility": "Treatment Facility"
};

const pcpPermissions = [
  "app.PCP.userProfile.permissions/canViewBHData",
  "app.PCP.userProfile.permissions/canViewReferralDetails",
  "app.PCP.userProfile.permissions/canCreateNewCurbside",
  "app.PCP.userProfile.permissions/canCreateNewReferral",
  "app.PCP.userProfile.permissions/canLoginPCPApp",
  "app.PCP.userProfile.permissions/canApproveMySuggestedPatients",
];

const practiceTitle = [
  'app.PCP.userProfile.practiceTitle/primaryCarePhysician',
  'app.PCP.userProfile.practiceTitle/nursePractitioner',
  'app.PCP.userProfile.practiceTitle/officeManager',
  'app.PCP.userProfile.practiceTitle/caseManager',
  'app.PCP.userProfile.practiceTitle/physiciansAssistant',
  'app.PCP.userProfile.practiceTitle/medicalAssistant',
  'app.PCP.userProfile.practiceTitle/socialWorker'
];

const regions = ['MA', 'PA', 'WA'];



export default {
  ageSpecialties: Object.keys(ageSpecialties),
  conditions: Object.keys(conditions),
  insurances: Object.keys(insurances),
  languages: Object.keys(languages),
  providerTypes: Object.keys(providerTypes),
  pcpPermissions: pcpPermissions,
  practiceTitle: practiceTitle,
  regions: regions
};
